### ISSUE TITLE
Broken packages v10

### ISSUE THREAD

**Issue by i-vyshnevska** [camptocamp/docker-odoo-project#129]
some updates are missing for python
bug appeared on tag 4.0.0, to reproduce it try to execute any test with pytest 
a stack trace 

    Traceback (most recent call last):
    File "/usr/local/bin/pytest", line 11, in <module>
    load_entry_point('pytest==5.3.2', 'console_scripts', 'pytest')()
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/usr/local/lib/python2.7/dist-packages/pytest/__init__.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
    File "/usr/local/lib/python2.7/dist-packages/_pytest/assertion/__init__.py", line 7, in <module>
    from _pytest.assertion import rewrite
    File "/usr/local/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py", line 205
    def _is_marked_for_rewrite(self, name: str, state):

**Comment by yvaucher** [comment]
Fixed by #142
